config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "homes#top"
  get "/homes/about" => "homes#about",as: "about"
  resources :users, only: [:show, :edit, :index, :create,]
  resources :books, only: [:destroy, :edit, :create,:index, :show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_one_attached :image
  belongs_to :user
  
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  
         
  has_many :books, dependent: :destroy
   
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    books_path
  end
  
  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
  
end

app/controllers/book_controller.rb
class BookController < ApplicationController
  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    @book.save
    redirect_to book_path
  end

  def index
    @book = Book.all
  end

  def show
  end
  
  private

  def book_params
    params.require(:book).permit(:title, :opinion)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
 

  def create
     @book = Book.new(book_params)
     @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "Book was successfully created."
      
      redirect_to book_path(@book.id)
    else @books = Book.all.order(id: :asc)
      render :index
    end
  end
    
  def index
    @book = Book.new
    @books = Book.all.order(id: :asc)
    
  end

  def edit
    Book.find(params[:id])
  end

  def show
    @book = Book.find(params[:id]) 
    @books = @user.books  
  end
  
  def destroy
    book = Book.find(params[:id]) 
    book.destroy 
    redirect_to '/books' 
  end
  
  private

  def book_params
    params.require(:book).permit(:title, :body, :image)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  
  protect_from_forgery
  
  def index
    @user = User.all
  end
  
  def show
    @user = User.find(params[:id])
    @book = @user.book
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  
  def create
    @user = User.index
    @user.user_id = current_user.id
    @user.save
    redirect_to user_path
  end
  
  private

  def user_params
    params.require(:user).permit(:title, :body)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_helper.rb
module BookHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
  
        <h2>User info</h2>
        <%= image_tag 'default-image' %>

          <table class="table">
            <tbody>
              <tr>
              <th>name</th>
              <th></th>
              </tr>
              <tr>
              <th>introduction</th>
              <th></th>
              </tr>
            </tbody>
          </table>

        <div class="row">
          <a class="btn btn-outline-secondary btn-block">
            <i class="fas fa-user-cog" aria-hidden="true">
              
            </i>
          </a>
        </div>



        <h2 class="mt-3">New book</h2>
        
        <%= form_with model: @book, url: '/books', method: :post do |f| %>

  
  
          <div class="group">
            <label for ="book_title">Title</label>
            <input class="form-control book_title" type="text" name="book[title]" id="book_title">
          </div>
    
          <div class="group">
            <label for ="book_body">Opinion</label>
            <textarea class="form-control book_body" type="text" name="book[body]" id="book_body"></textarea>
          </div>
  
          <div class="group">
            <input type="submit" name="commit" value="Create Book" class="actions btn btn-sm btn-success" date-disable-with="Create Book">
          </div>
        <% end %>
      
    </div>

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>
        <form enctype="multipart/form-date" action="/users/id" accept charset="UTF-8" method="post">
          <input type = "hidden" name ="_method" value="patch" autocompalte="off">
          
          <div class="form-group">
            <label for = "book_title">Title</label>
            <inout class="form-control name" type="text" name = "book[title]" id="book_title">
          </div>
          
          <div class="form-group">
            <label for ="book_opinion">Opinion</label>
            <textarea class="form-control book_body"  name="book[body]" id ="book_body">
            </textarea>
          </div>
          
          <div class="form-group">
            <input type="submit" name="commit" value="Update Book" class="btn btn-success" date-disable-with="Update Book">
          </div>
          
          <a class="book_title" href="/books/#{book.id}">Show</a>
           
          |
         <a class="back" href="/books">Back</a>
          
        </form>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
  
        <h2>User info</h2>
        
       
        <% if @book.image.attached? %>
          <%= image_tag book.image, size: "100x100" %>
        <% else %>
          <%= image_tag 'default-image', size: "100x100" %>
        <% end %>

          <table class="table">
            <tbody>
              <tr>
              <th>name</th>
              <th></th>
              </tr>
              <tr>
              <th>introduction</th>
              <th></th>
              </tr>
            </tbody>
          </table>
          
          
          <div class="row">
              
          <a class="btn btn-outline-secondary btn-block">
              <i class="fas fa-user-cog" aria-hidden="true"></i>
              </a>
          
          </div>
       

        <h1>New Book</h1>
        <%= form_with model: @book, url: '/books', method: :post do |f| %>
        <h4>Title</h4>
          <%= f.text_field :title %>
	
        <h4>Opinion</h4>
          <%= f.text_area :body %>
	
        
          <%= f.submit 'Create Book' %>
    
        <% end %>
        </div>
    
    
    <div class="col-md-8 offset-md-1">
        <h2>Books</h2>
        <% @books.each do |book| %>
       
        <table class="table table-hover table-inverse">
          <thead>
          <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
          <th colspan="3"></th>
          </tr>
          </thead>
          
          <tbody>
            <tr>
              <td><% if @book.image.attached? %>
                    <%= image_tag book.image, size: "80x80" %>
                  <% else %>
                    <%= image_tag 'default-image', size: "80x80" %>
                  <% end %></td>
              <td><%= link_to book.title, book_path(book.id) %></td>
            </tr>
          </tbody>
        </table>
         <% end %>
        
    </div>
    
    
    
    </div>
    </div>

app/views/books/new.html.erb
<h1>New book</h1>
   <%= form_with model: @book do |f| %>
   
    <h4>Title</h4>
      <%= f.text_field :title %>
      
    <h4>Opinion</h4>
      <%= f.text_area :body %>
      
      <%= f.submit 'Create Book' %>
  <% end %>

app/views/books/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
  
        <h2>User info</h2>
        <%= image_tag 'default-image' %>

          <table class="table">
            <tbody>
              <tr>
              <th>name</th>
              <th></th>
              </tr>
              <tr>
              <th>introduction</th>
              <th></th>
              </tr>
            </tbody>
          </table>
          

        <div class="row">
          <a class="btn btn-outline-secondary btn-block">
            <i class="fas fa-user-cog" aria-hidden="true">
              
            </i>
          </a>
        </div>



        <h2 class="mt-3">New book</h2>
        
        <%= form_with model: @book, url: '/books', method: :post do |f| %>
  
  
        <h4>Title</h4>
          <%= f.text_field :title %>
	
        <h4>Opinion</h4>
          <%= f.text_area :body %>
	
          <%= f.submit 'Create Book' %>
    
        <% end %>
      </div>
        
      
      <div class="col-md-8 offset-md-1">
        <h2>Book detail</h2>
        <table class="table">
          <tbody>
           <tr>
            <td>
              <% if @book.image.attached? %>
                <%= image_tag book.image, size: "100x100" %>
              <% else %>
                <%= image_tag 'default-image', size: "100x100" %>
              <% end %>
            </td>
            <td></td>
            <td>  <% if @book.user == current_user %>
                  <%= link_to "Edit", edit_book_path(@book.id) %>
                  <% end %></td>
                  
            <td>  <% if @book.user == current_user %>
                  <%= link_to "Destroy", book_path(@book), method: :delete %>
                  <% end %>
            </td>
           </tr>
           </tbody>
         </table>
      </div>
      
      
    </div>

app/views/homes/about.html.erb
<div class="container">
        <div class="row">
                        

   
        <h1 class="px-3 mx-auto">Welcome to
        <i class ="fas fa-book" aria-hidden="true">
        </i>
        <strong>Bookers</strong>!
        </h1>
            </div>
        </div
        </div>
</div>

app/views/homes/top.html.erb
<div class="container">
        <div class="row">
            <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
        

    <h1>welcome to
        <i class ="fas fa-book" aria-hidden="true">
        </i>
        <strong>Bookers</strong>!!
        </h1>
        
<p>In<i class ="fas fa-book" aria-hidden="true"></i> 
<strong>Bookers</strong>,</p>

<p>you can share and exchange your opinions , inpressions , and emotions</p>

<p>about various books!</p>

    <div class="btn-wrapper col-10 mx-auto">
    <div class="row">
        <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
    </div>
    
    
    <div class="row">
        <a class="btn btn-success btn-sm btn-block md-3 sign_up" href="/users/sign_up">Sign up</a>
    </div>
    </div>
    
            </div>
        </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/06d5403368.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark ">
        <div class="container">
          <a class="navbar-brand text-white" href="/">
          <span>Bookers</span>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
          <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to "Home", books_path, class: 'nav-link text-white' %>
            </li>
            
            <li class="nav-item">
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: 'nav-link text-white' %>
            </li>
            
            
           
          <% else %>
           
            <li class="nav-item">
              <%= link_to "About", about_path, class: 'nav-link text-white' %>
            </li>
            <li class="nav-item">
              <%= link_to "Sign up", new_user_registration_path, class: 'nav-link text-white' %>
            </li>
            <li class="nav-item">
              <%= link_to "Log in", new_user_session_path, class: 'nav-link text-white' %>
            </li>
            
          <% end %>
            </ul>
            
          </div>
        </div>
      </nav>
    </header>
    
    
    <main>
      <p id = "notice"></p>
  
        
    </div>
       
    <%= yield %>
    </main>
    <footer class="bg-wite text-black px-auto mx-auto  ">
        <div class="container mt-5">
          <div class="row">
            <div class= "mx-auto">
            <p>CopyRight Infratop.inc</p>
        </div>
    
      </div>
      </div>
    </footer>
  </body>
  </body>
</html>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>
        <form enctype="multipart/form-date" action="/users/id" accept charset="UTF-8" method="post">
          <input type = "hidden" name ="_method" value="patch" autocompalte="off">
          
          <div class="form-group">
            <label for = "user_name">Name</label>
            <inout class="form-control name" type="text" name = "user[name]" id="user_name">
          </div>
          
          <div class="form-group">
            <label for ="user_image">Image</label>
            <input class="form-control-file user image" accept="image/*" type="file" name="user[profile_image]" id ="user_profile_image">
          </div>
          
          <div class="form-group">
            <label for ="user_introduction">Introduction</label>
            <textarea class="form-control introdction" name="user[introdction]" id="user_introdction">
            </textarea>
          </div>
          
          <div class="form-group">
            <input type="submit" name="commit" value="Update User" class="btn btn-secondary" date-disable-with="Update User">
          </div>
          
          
        </form>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
  
        <h2>User info</h2>
        <%= image_tag 'default-image' %>

          <table class="table">
            <tbody>
              <tr>
              <th>name</th>
              <th></th>
              </tr>
              <tr>
              <th>introduction</th>
              <th></th>
              </tr>
            </tbody>
          </table>

        <div class="row">
          <a class="btn btn-outline-secondary btn-block">
            <i class="fas fa-user-cog" aria-hidden="true">
              
            </i>
          </a>
        </div>


        
        <h2 class="mt-3">New book</h2>
        <%= form_with model: @book, url: '/book', method: :post do |f| %>
        <h4>Title</h4>
          <%= f.text_field :title %>
	
        <h4>Opinion</h4>
          <%= f.text_area :body %>
	
          <%= f.submit 'Create Book' %>
          
          <% end %>

  
  
   </div>
    
          
        <div class="col-md-8 offset-md-1">
        <h2>Books</h2>
        <table class="table table-hover table-inverse">
          <thead>
          <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
          <th colspan="3"></th>
          </tr>
          </thead>
        </table>
     
        
        </div>
    
    
    
    
    </div>
    </div>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
  
        <h2>User info</h2>
        <%= image_tag 'default-image' %>

          <table class="table">
            <tbody>
              <tr>
              <th>name</th>
              <th></th>
              </tr>
              <tr>
              <th>introduction</th>
              <th></th>
              </tr>
            </tbody>
          </table>

        <div class="row">
          <a class="btn btn-outline-secondary btn-block">
            <i class="fas fa-user-cog" aria-hidden="true">
              
            </i>
          </a>
        </div>



        <h2 class="mt-3">New book</h2>
        
        <%= form_with model: @book, url: '/books', method: :post do |f| %>

  
  
          <div class="group">
            <label for ="book_title">Title</label>
            <input class="form-control book_title" type="text" name="book[title]" id="book_title">
          </div>
    
          <div class="group">
            <label for ="book_body">Opinion</label>
            <textarea class="form-control book_body" type="text" name="book[body]" id="book_body"></textarea>
          </div>
  
          <div class="group">
            <input type="submit" name="commit" value="Create Book" class="actions btn btn-sm btn-success" date-disable-with="Create Book">
          </div>
        <% end %>
      
    </div>
    
          
        <div class="col-md-8 offset-md-1">
        <h2>Books</h2>
        <table class="table table-hover table-inverse">
          <thead>
          <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
          <th colspan="3"></th>
          </tr>
          </thead>
        </table>
     
        
        </div>
    
    
    
    
    </div>
    </div>